name = "promatch2025"
main = "src/worker.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

# Static Assets設定
[assets]
directory = "dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

# 開発環境
[env.development]
name = "promachi-dev"

# ステージング環境  
[env.staging]
name = "promachi-staging"

# 本番環境
[env.production] 
name = "promatch2025"

# デフォルト（本番）データベース
[[d1_databases]]
binding = "DB"
database_name = "project-matching-platform-prod"
database_id = "ae2d3382-04af-4075-8e84-e3e99ae60761"

[[env.production.d1_databases]]
binding = "DB"
database_name = "project-matching-platform-prod"
database_id = "ae2d3382-04af-4075-8e84-e3e99ae60761"

# 開発環境用D1データベース
[[env.development.d1_databases]]
binding = "DB"
database_name = "project-matching-platform-db"
database_id = "e16ae3f5-eb7f-456a-9e9e-849f47a09e06"

# 環境変数は後で設定
# [env.production.vars]
# JWT_SECRET = "will-be-set-via-wrangler-secret"